### ISSUE TITLE
Multi-component failing on WIN10

### ISSUE THREAD

**Issue by tuomohopia** [haskell/ghcide#605]
I can't get multi-component setup working with any `hie.yaml` configuration that I've tried.

I just installed the latest `ghcide` with:
```sh
stack --resolver lts-15.15 install
```

Now , when I define `hie.yaml` like this:
```yaml
cradle:
  stack:
    - path: "./src"
      component: "my-api:lib"
    - path: "./test"
      component: "my-api:test:integration-tests"
```

VSCode acts as if no ghcide installed. Its Output panel for `ghcide` gives me this:
https://pastebin.com/NZXCbAHH

Running `ghcide` in the project folder in Powershell terminal gives me this:
https://pastebin.com/wkMsuGT5

For the record, when I just specify the `hie.yaml` file as:
```
cradle: {stack: {component: "my-api:lib" }}
```
It works fine. But just for the `lib` files inside my `src`, not the test folder. Basically works as a single-component setup this way.

I'm on
* WIN10
* Vscode
* stack, but specify project with a `.cabal` file

Based on discussions on Slack I suspect this may be a WIN10 specific problem.
