### ISSUE TITLE
directory with code not mentioned in cabal file is included by ghcide

### ISSUE THREAD

**Issue by andrewufrank** [haskell/ghcide#648]
I have constructed a minimal project to learn how to use ghcide. The directory includes a main and a library. It contains an additioanl directory `tests` which is not included in the cabal file (and not ready to compile). `ghcide` includes these files, which it should not. 

The messages are:

 `Could not find module ‘Test.Framework’
  It is not a module in the current program, or in any known package. `

and at the end it says:  `Completed (4 files worked, 3 files failed)`

The code is `https://github.com/andrewufrank/minimalForTest.git `  there is a master branch  with the `tests` directory and another one `no-tests-dir` which has no `tests` directory and thus `ghcide` works perfectly.

**Comment by fendor** [comment]
Hi! 

So, essentially the problem is that build-tools do not give us the information we need to really know when a file is part of package.
In this case, due to the existence of `stack.yaml`, we assume that you are using stack for building the project. 
When you open a file, we try to find the compilation options required for this file.
We try to find the compilation flags by executing `stack repl` and intercept the options that are passed to `ghci`. 
In this case, `stack repl` succeeds, since it isnt even aware of the filepath we are looking for. 
Note, we can not use `stack repl tests/Testing.hs`, because stack will only compute a partial module graph, which you generally do not want! 

When you are using `cabal`, the behaviour is as expected (delete stack.yaml)
```bash
> hie-bios flags tests/Testing.hs
Failed to show flags for "tests/Testing.hs": 
["Failed to parse result of calling cabal"
,""
,"cabal: Unknown target 'tests/Testing.hs'.\nThe package TestSimple has no file target 'tests/Testing.hs'.\n\n\n"
,""
]
``` 

However, what you actually want is to ignore certain directories. You can achieve that by using a configuration file `hie.yaml` and specify how to load you project. (Reference https://github.com/mpickering/hie-bios)
For your particular project, the `hie.yaml` you want looks like:
```yaml
cradle:
  multi:
    - path: ./tests
      config:
        cradle:
          none: # Do not even attempt to load this directory
    - path: ./ # for everything else, load it with stack
      config:
        cradle:
          stack:
```

So, this configuration tells ghcide (and Haskell Language Server and Haskell IDE Engine, all three of those use this format) to not attempt to load anything from `./tests` and for everything else, it should use `stack` (or essentially `stack repl`).
If `stack repl` is not enough to load your project (usually when you have multiple executables), you can specify an exact mapping from a directory to a component. For your project:

```yaml
cradle:
  multi:
    - path: ./tests
      config:
        cradle:
          none: # Do not even attempt to load this directory
    - path: ./ # for everything else, load it with stack
      config:
        cradle:
          stack:
            # Special short-hand syntax since you need it quite often
            - path: ./
              component: "SimpleTest:lib"
            - path: ./src/ClassMain.hs
              component: "SimpleTest:exe:foo"
```
Whenever you trying to `./src/ClassMain.hs`, we essentially perform a `stack repl SimpleTest:exe:foo` to load the component.
This component syntax exists for both cabal and stack and is slightly different for each :).

This behaviour cannot easily be improved unless the different tools give us the information we need to actually know the full project.
